### ISSUE TITLE
Should we have versioning on the API?

### ISSUE THREAD

**Issue by batpad** [developmentseed/observe-api#19]
Should we prefix all API routes with `/v1/` or so, to allow for versioning of the API?

Especially with a mobile app where we often cannot ensure all users update at the same time (unlike a webpage), it's sometimes useful to have this escape hatch in case we need to change things, to have a straightforward scheme to keep things working for older clients that may not have updated.

Ideally, we would never need to make a breaking change like that, but if we do, it allows us to represent versions of the API cleanly in the URLs (and have clear deprecation plans of older versions, etc.).

@vgeorge @geohacker @sethvincent thoughts?

**Comment by vgeorge** [comment]
As discussed in today's scrum, we are going to implement an endpoint to inform the minimum required versions for clients, as described at #23, so them can show a nice message asking the user to update the app.
