### ISSUE TITLE
Login using OSM OAuth

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe-api#2]
See https://github.com/developmentseed/observe/issues/89#issue-494641709.

**Comment by vgeorge** [comment]
We implemented OAuth and the endpoint `/login` is generating a JWT. But we are missing a final step, which is to redirect to the frontend/mobile to pass the JWT token. 

Looking at Hapi docs its not super clear how this would work. At Feathers docs there is a [example workflow](https://docs.feathersjs.com/api/authentication/oauth.html#redirects) that might work for us. Basically, after login, the client would be redirected to a passed URL with a window location hash including the access token. 

For the dashboard, it would be something like:

- http://observe.web/login#accessToken=the_jwt_token

For mobile, it could be something like observe://login#accessToken=the_jwt_token. 

But I'm not sure if the approach in mobile is right. It seems that deeplinking is not something straightforward to implement in both platforms. It would be nice to check for examples. 

@batpad please let me know what you think.

**Comment by batpad** [comment]
To clarify, for now, if the backend can:

 - Accept a callback URL, testing with something like http://observe.web/login#accessToken=the_jwt_token should be good
 - Ideally, also maintain a whitelist of allowed callback URLs

If the above works, I don't think we would need to change anything in the backend to get the auth working on the mobile app - it would then just be figuring out things within the mobile app code.

**Comment by vgeorge** [comment]
I believe we can't implement callback URL as query parameter with OAuth 1. The auth provider will always return to the predefined URL. 

A solution is, at `/login` route after OAuth process, check if the [user agent is mobile](https://stackoverflow.com/questions/3514784/what-is-the-best-way-to-detect-a-mobile-device) and redirect it to the Observe deep link.

**Comment by vgeorge** [comment]
Please see PR #15. Instead of checking if client is mobile, there will be a different route for mobile app authentication.

**Comment by vgeorge** [comment]
Solved by #15, please reopen if any issue is found.
