### ISSUE TITLE
Define image resolutions

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe-api#20]
Currently the API is saving images in [two sizes](https://github.com/developmentseed/observe-api/blob/0ca3b23c30e35b1f82b97a4c565b66cb2e9ef80c/config/default.json#L20-L32), making them [fit inside](https://github.com/developmentseed/observe-api/blob/6ceed83190253197c7d20ff1023b900e2266f0ec/app/services/media-store.js#L58) the defined resolution.

@batpad suggested [not to use "inside" strategy](https://github.com/developmentseed/observe-api/pull/17#discussion_r337945737). 

@LanesGood do you already have clear idea on which sizes do we need or should we wait a little bit? I believe this is not a blocker now, as we can add/change sizes easily via config files.

**Comment by LanesGood** [comment]
@vgeorge no major size expectations here, except to state that I don't envision a use case for very high-res images. 

However, 800x600 may be too low for even expected use. It looks like Mapillary is taking in full-res images - 4032x2268 and higher. This is useful for providing street-view detail for navigation apps. For Observe mapping in Josm or other editors, I think that a resolution of 1200px on the longest edge will allow adequate detail for finding features in a photo, and referencing later on. It looks like Mapeo is also using 1200 as a set resolution for their [resized image function](https://github.com/digidem/mapeo-mobile/blob/8a572e142e7f6a3115393dce727eb0687149f811/src/frontend/hooks/useDraftObservation.js#L31).

**Comment by batpad** [comment]
I'd be :+1: for doing 1200x1200 with the `fit`: `inside` strategy for the larger image.

For the smaller thumbnails, I'd actually be in favour of doing like 100x100 with a center cropping strategy, if that makes sense. This way, we guarantee that the smaller thumbnails are all the exact same dimensions, which probably works better visually for a list view.

**Comment by vgeorge** [comment]
Implemented in three sizes: `thumbnail`, `default` and `full`. I thought it would be useful to have an intermediate size for quicker load/display at the frontend.

https://github.com/developmentseed/observe-api/blob/3fa519b61c046fd266b4a6953e211d1f61554cc7/config/default.json#L23-L42
