### ISSUE TITLE
Login error after sign up

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe-api#27]
Login only works after second attempt. Both Lane and I received this error at the popup page:

```
502 Bad Gateway
nginx/1.16.1
```

**Comment by batpad** [comment]
@vgeorge can you say how one would reproduce this?

**Comment by vgeorge** [comment]
Run the dashboard locally pointing to the remote API. If you user doesn't exist, this error should happen. I believe the same error happen when running agaisng a local API and your user doesn't exist.

**Comment by vgeorge** [comment]
This was fixed and deployed. Please reopen if there is any issue at the first login.
