### ISSUE TITLE
Data Schema - Photos > OSM Objects

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe-api#31]
In #4 data schema @vgeorge lays out the osmObjects property of Photos as:
> osmObjects: array of strings, will contain osm ids like node/2932938, way/10203932, relation/102293, etc

Vitor pointed out that we need to clarify what it means to have multiple OSM Objects associated with a photo. There are a few options to consider here:
- Option 1) We take the position that a single OSM Object can have multiple photos, but a single photo can only be associated with one OSM Object. This is the most probable use case, where users take a photo intended to represent a single feature, way, etc. This would require changing the data schema.
- Alternatively, we could allow users to associate a photo with multiple OSM objects. The use case here is taking a photo of multiple features, and then linking that one photo to those objects. This is a bit less clear from both the UX and data side of things but would not require changing the data model. It would definitely require adding some guidelines to the app for photo association

@vgeorge any options I missed?

**Comment by vgeorge** [comment]
@LanesGood thanks for writing this, I believe it covers well. If @developmentseed/observe agrees, I'll change the photo-osmObject relation from many-to-many to one-many by changing the type to a string here:

https://github.com/developmentseed/observe-api/blob/develop/migrations/20191017122308_add-photos.js#L5

**Comment by vgeorge** [comment]
Implemented.
