### ISSUE TITLE
Route /traces

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe-api#6]
Endpoint for GPX traces related actions. I believe we need to validate the schema at #4 before detailing this.

**Comment by vgeorge** [comment]
Actions for traces:

- GET: Returns trace as GeoJSON, with meta included in properties. In order to allow [opening the trace in JOSM](https://github.com/developmentseed/observe-dashboard/issues/9), this method should also accept an optional `format=osm` query parameter to allow passing a OSM XML URL to import command of [JOSM Remote Control](https://wiki.openstreetmap.org/wiki/JOSM/RemoteControl)
- POST: Creates a new trace from a valid GPX file
- PUT: Probably not supported, if there will be no `label` or other properties for traces (see https://github.com/developmentseed/observe-api/issues/4)
- DELETE: Remove trace

**Comment by batpad** [comment]
> POST: Creates a new trace from a valid GPX file

I'm more inclined to have the POST format to match the default GET GeoJSON format - it seems a bit more straightforward on the client and probably easier to parse. Then we export either `osm` or `gpx` formats only when requested as such, but stick to the GeoJSON format as the default interchange? @geohacker @vgeorge do you have strong feelings either way about this?

**Comment by geohacker** [comment]
Yeah I agree to keep POST and GET requests consistent with the format. We would have a geojson on the clientside as we want to show the trace on mapbox gl so posting that directly makes sense to me and we can convert them to gpx / osm on the API?

**Comment by vgeorge** [comment]
Ok, I've changed the POST method to accept a GeoJSON feature. Should we adopt [tracejson](https://github.com/sharedstreets/tracejson) for that?

**Comment by geohacker** [comment]
TraceJSON sounds good to me!

**Comment by vgeorge** [comment]
Implemented by https://github.com/developmentseed/observe-api/pull/16.
