### ISSUE TITLE
Surveys

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe-api#63]
We’ve previously outlined the basic idea of adding surveys to Observe through an API. This ticket will outline one approach to implementing surveys. 

## Questions
- Questions are what the user will answer when they are in the field
- Questions are immutable. This is to prevent people from altering the meaning of the question mid-survey rendering the data inconsistent
- When a user edits a question, it creates a new version of the question. Surveys always use the latest version of the question.
- A question has a text, type, and optional options. 
- Types could be checkboxes, multiple choice, dropdown, photo, date and time
- A question can be part of many surveys

### Model definition

- `id`, integer
- `version_id`, version_id, foreign key
- `label`, string
- `type`, enum (checkbox, multiple_choice, dropdown, photo, date and time)
- `options`, json

## Question versions
- `id`, integer
- `question_id`, integer
- `version`, integer

## Surveys
- A survey is a set of questions
- Surveys are versioned. This allows users to add/modify/remove questions
- Editing a survey would create a new version of the survey
- A survey can have questions from another survey

### Model definition

- `id`, integer
- `name`, string
- `created_at`, timestamp
- `created_by` / `user`, user_id, foreign key
- `questions`, array of question_ids, foreign key

## Observations
- Observations are responses to surveys from a user
- Observations are associated with OSM objects
- An Observation can be associated with only one OSM object
- Observations have a timestamp, username, survey id, survey version, question id

### Model definition

- `id`, integer
- `created_at`, timestamp
- `created_by`/`user`, user_id, foreign key,
- `survey_id`, survey_id, foreign key,
- `response`/`answers`, json {`question_id`: ‘answer’, `question_id2`: `answer2`}
- `osm_feature`, string, `node/123344/v1` — this could also be three columns

## Answers
- Answers to individual questions in a response
- Answers are associated with Observations

### Model definition
- `id`, integer
-  `observation_id`, foreign key
- `question_id`, question_id, foreign key
- `question_version`
- `answer`, value of the answer, string

## OSM objects
- Surveys are associated with OSM objects
- Adding a survey to an OSM object will copy over them to Observe
- An OSM object can have multiple Observations

### Model definition

- `id`, integer
- `osm_feature_id`
- `observations`, array of observation_ids, foreign key
- `geometry`, geometry
- `attributes`, json

Things that we will ticket separately
* How to keep the data in sync between observations and OSM

cc @developmentseed/observe

**Comment by vgeorge** [comment]
Implemented in `develop` branch.
