### ISSUE TITLE
Return Gravatar hash in user payload

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe-api#89]
This is a public route and should not return the user's email.

**Comment by vgeorge** [comment]
In fact, we need the user email as gravatar hash in order to display the profile pic. Reference:

https://en.gravatar.com/site/implement/images/

**Comment by kamicut** [comment]
Ah, we're not returning the user's email?

**Comment by vgeorge** [comment]
It is, but we should hide it and send email hash instead, to be able to display profile pic from gravatar.
